NGO_donation/Controllers/ReguserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using NGO_donation.Models;

namespace NGO_donation.Controllers
{
    public class ReguserController : Controller
    {
        private DonationEntities db = new DonationEntities();

        // GET: Reguser
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
    //    [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "firstname,lastname,cma_,phone,emailid,address1,address2,city,state,zipcode,country,urbanization")] tbl_registeruserdetail tbl_registeruserdetail)
        {
            if (ModelState.IsValid)
            {
                db.tbl_registeruserdetail.Add(tbl_registeruserdetail);
                db.SaveChanges();
                int regid = tbl_registeruserdetail.regid;
                Session["RegId"] = regid;
                ViewData["Success"] = "Registration place successfully.";
                return RedirectToAction("DonationAmount", "DonationType");
            }
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NGO_donation/Views/Shared/Layout1.cshtml
<!DOCTYPE html>
<html>
<head>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Html.Partial("_header")

    
</head>
<body>
    <div class="col-md-3" style="">
        <div class="list-group">
            <a href="~/UserManage/Index" class="list-group-item list-group-item-actions" style="background-color:#dff0d8;"> User Management </a>
            <a href="~/Donationdetails/Index" class="list-group-item list-group-item-action" style="background-color:#dff0d8"> Donation Management </a>
            @*<a href="~/UserManage/Index" class="list-group-item list-group-item-action" style="background-color:#dff0d8"> User View </a>*@
        </div>
    </div>




    <div class="col-lg-offset-3">@RenderBody()</div>
    

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous" style=""></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous" style=""></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous" style=""></script>


    <div class="container body-content">

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - NGO Donation Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

NGO_donation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - NGO Donation</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <header style="background-color: #dff0d8;">

        <div>
            <p style="margin-left:10px;float:left;font-size:large;font-family:'Times New Roman', Times, serif;font-style:italic;font-weight:bold;font-stretch:wider;">
                NGO<img src="~/Content/ImgDonate.jpg" style="width:100px;" />Helping Hands are better than Praying Lips!
            </p>
            <p style="text-align:right">
                <img src="~/Content/UserIcon.png" style="width:50px" />
            </p>
        </div>
    </header>
</head>
<body>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - NGO Donation Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NGO_donation/Views/Shared/_RegularUserLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - NGO Donation</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NGO Donation", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("User Management", "Index", "Reguser")</li>
                    <li>@Html.ActionLink("Event Management", "Index", "Reguser")</li>
                    <li>@Html.ActionLink("User View", "Index", "Reguser")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NGO_donation/Views/Shared/_header.cshtml
<!doctype html>

<header style="background-color: #dff0d8;">

    <div>
        <p style="margin-left:10px;float:left;font-size:large;font-family:'Times New Roman', Times, serif;font-style:italic;font-weight:bold;font-stretch:wider;">
            NGO<img src="~/Content/ImgDonate.jpg" style="width:100px;" />Helping Hands are better than Praying Lips!
        </p>
        <p style="text-align:right">
            @if (Session["firstname"] != null)
            {
                <label>
                    @Session["firstname"]
                </label>
            }
            @if (Session["lastname"] != null)
            {
                <label>
                    @Session["lastname"]
                </label>
            }
            (
            @if (Session["role"] != null)
            {
                <label>
                    @Session["role"]
                </label>
            }
            )
            @Html.ActionLink("Log out", "Index", "Home")
            <img src="~/Content/UserIcon.png" style="width:50px" />

        </p>
    </div>
</header>